source 'https://github.com/FFComment/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

target 'FFIMKit_Example' do
  pod 'FFIMKit', :path => '../'
  target 'FFIMKit_Tests' do
    inherit! :search_paths

    
  end
end
